const express=require('express');
const router=express.Router();
const homeController=require('../controllers/home_controller');
router.get('/',homeController.home);
router.get('/register',homeController.register);
router.get('/contact',homeController.contact);
router.get('/login',homeController.login);
router.get('/register',homeController.register);
router.get('/shopping-cart',homeController.shoppingCart);
router.use('/api',require('./api'));
module.exports=router;